<?php
$phone = $_POST['phone'];
$gender = $_POST['gender'];
$child = $_POST['child'];
$creditor1 = $_POST['creditor1'];
$creditor2 = $_POST['creditor2'];
$creditor3 = $_POST['creditor3'];
$property1 = $_POST['property1'];
$property2 = $_POST['property2'];
$property3 = $_POST['property3'];
$property4 = $_POST['property4'];
$property5 = $_POST['property5'];
$property6 = $_POST['property6'];
$property7 = $_POST['property7'];
$property8 = $_POST['property8'];
$marrige = $_POST['marrige'];

// $nm = $_POST['nm'];
// $nm = $_POST['nm'];
// $nm = $_POST['nm'];
// $nm = $_POST['nm'];
// $nm = $_POST['nm'];
// $nm = $_POST['nm'];
// $nm = $_POST['nm'];
print '성별 : ' . $gender . '<br>';
print '연락처 : ' . $phone . '<br>';
print '자녀 유무 : '. $child . '<br>';
print '혼인 유무 : '. $marrige . '<br>';
print '채권자수 : ' . $creditor1 . '개<br>';
print '무담보 채무액 : 총 ' . $creditor2 . '만원<br>';
print '담보 채무액 : 총 ' . $creditor3 . '만원<br>';
print '거주형태 : ' . $property1 . '<br>';
print '자가-부동산 실소유자 : ' . $property2 . '<br>';
print '자가-부동산 시세 : ' . $property3 . '<br>';
print '전월세-계약자 : ' . $property4 . '<br>';
print '전월세-보증금,월세 : ' . $property5 . '<br>';
print '전월세-보증금 담보대출금액 : ' . $property6 . '<br>';
print '차량 소유 : ' . $property7 . '<br>';
print '차량 시세 : ' . $property8 . '<br>';

